### PR TITLE
rbenv role

### PR DESCRIPTION
**Pull request by ghn**
Very handy to install custom ruby version https://github.com/rbenv/rbenv

Thought I could install with debian packages but latest version available is 2.2.0-preview1, not 2.4.0!

* This PR is a : New feature

### CODE REVIEW

**Comment by jeanmonod** [comment]
But what would be the usage of {rbenv} in drifter? I mean {rbenv} is too managed multiple environnements on a single host. But while would you do that into a vagrant box? Usually you are using your box for a single project...

**Comment by ghn** [comment]
It's usefull so you can choose which version you want for your project. Just like PHP where you cant set the version.

**Comment by krtek4** [comment]
I would say it would be useful to have a ruby role where you can choose the version as it is now the case with PHP, but a role for just rbenv makes no sense IHMO.

rbenv is an implementation detail to install various ruby version, and as such should not be exposed to the end user. The goal is to choose the version you want to install, rbenv is just the mean to this.

Also, I would prefer using the ruby version from debian repositories whenever possible as they would be the one available on the production server most of the time anyway.

**Comment by ghn** [comment]
I agree, this is what I wanted to do afterwards: update the ruby role.

Then it's just a matter of taste. As a ruby dev I'd find handy to have this role along with the ruby one.

About your last comment I can only disagree. Debian package is old and doesn't provide the latest version (for instance: imagine I want version 2.4 which is already supported by heroku)

**Comment by sephii** [comment]
From what I can see rbenv doesn't directly ship Ruby versions, so you'd be just fine by installing rbenv from the Debian package and ruby-build from Github. That said, since you need to install ruby-build from Github anyway I wouldn't mind that rbenv also gets installed from Github. Now if you install them from Github please target a specific tag instead of using the master branch ([you can use the `version` parameter in the `git` role for that](http://docs.ansible.com/ansible/git_module.html)), otherwise it could cause isolated bugs depending when the box was created.

As for the Ansible role separation, except if there's a good reason for someone to not use rbenv, I would bundle this directly with the ruby role, so that we always use the same method to install Ruby in Drifter boxes. I would then use a parameter (like `python_version` in the Python role) to define which version should be used, with a sensible default.

Thanks! :guitar:

**Comment by krtek4** [comment]
https://packages.debian.org/search?keywords=ruby-build

**Comment by sephii** [comment]
@krtek4 I gave it a try and the latest stable version of Ruby you can install is 2.1.0 (released in 2013, latest is 2.4.0), so it's not very useful.

**Comment by ghn** [comment]
Ok, sounds good. I'll will bundle it directly in the ruby role + set the tag.
Will do it in another branch. So We can close this PR

**Pull request closed without merging**
