### PR TITLE
Unify default installed PHP extensions

### PR DESCRIPTION
**Pull request by thePanz**
[Quick description of your PR and motivation.]

* This PR is a : Bugfix

### CODE REVIEW

**Comment by sephii** [comment]
Thanks! 🐟

**Comment by sephii** [comment]
I had to revert this patch because Debian doesn't have some of the packages. Could you have a look? https://github.com/liip/drifter/commit/bbbc68ea6fbf9e1eaee7b760b66fa373521fc00f

**Comment by thePanz** [comment]
I tested with `drifter/jessie64-base` and manually changed the `provisioning/roles/php/vars/Debian-7.x.yml` file with the one provided here, it worked with no issues.

Which Debian version did you use?

**Comment by sephii** [comment]
I used `drifter/jessie64-base` and left the defaults for the PHP version, which means installing PHP 5.6, not PHP 7.

If I checkout the commit 13a160330358577d13d5eaf48000d6a14560c2da (right before the revert) and just enable the `php-fpm` role in the playground playbook and run `vagrant up` that's what I get:

```
TASK [php : install PHP packages] **********************************************
failed: [default] (item=[u'php5-common', u'php5-cli', u'php5-curl', u'php5-intl', u'php5-gd', u'php5-sqlite', u'php5-imagick', u'php5-bcmath', u'php5-mbstring', u'php5-readline', u'php5-soap', u'php5-xml', u'php5-zip']) => {"failed": true, "item": ["php5-common", "php5-cli", "php5-curl", "php5-intl", "php5-gd", "php5-sqlite", "php5-imagick", "php5-bcmath", "php5-mbstring", "php5-readline", "php5-soap", "php5-xml", "php5-zip"], "msg": "No package matching 'php5-bcmath' is available"}
```

These packages don't exist in the official Debian packages repository nor in dotdeb. Also it seems that https://github.com/liip/drifter/commit/1dc3e0063c688e4bb4765cb29aefd296b2187b2c#diff-184e176acf5b0f541cfb4710d8e641f7 introduced a bug because dotdeb source is not installed anymore for PHP < 7.

**Pull request merged**
