### PR TITLE
Replace sudo/sudo_user by become/become_user; the former is now deprecated

### PR DESCRIPTION
**Pull request by OdyX**

### CODE REVIEW

**Comment by krtek4** [comment]
If I've read the documentation correctly, `become` was first introduced in Ansible 1.9.

The current Jessie version is 1.7.2 if you don't have the backports activated.

Drifter should correclty work with version 1.6.2, so I think it may be a bit early to merge this.

@sephii @OdyX any opinion on this ?

**Comment by sephii** [comment]
Do we have any idea of their deprecation policy? Until when will this option be supported?

**Comment by krtek4** [comment]
http://docs.ansible.com/ansible/become.html

> Before 1.9 Ansible mostly allowed the use of sudo and a limited use of su to allow a login/remote user to become a different user and execute tasks, create resources with the 2nd user’s permissions. As of 1.9 become supersedes the old sudo/su, while still being backwards compatible. This new system also makes it easier to add other privilege escalation tools like pbrun (Powerbroker), pfexec and others.

> For those using old playbooks will not need to be changed, even though they are deprecated, sudo and su directives, variables and options will continue to work. It is recommended to move to become as they may be retired at one point.

Not really clear to me what they intend to do

**Comment by krtek4** [comment]
With the incoming changes on `ansible_local` (see #70) that would finally make it more or less usable on all out platforms, it may be the time to merge this as `ansible_local` is the default anyway.

Any thought  @sephii  @OdyX  ?

**Comment by sephii** [comment]
Yes we should merge this once `ansible_local` can be used everywhere. We should just probably update this PR to make sure new occurrences of `sudo` are replaced.

**Comment by krtek4** [comment]
Just merged https://github.com/liip/drifter/pull/92

With the new boxes, it might be the time to go forward with this... I'll have a look next week to cleanup everything related to `sudo`

**Pull request merged**
