### PR TITLE
Role:PostGIS add support for Debian Buster and drop Wheezy

### PR DESCRIPTION
**Pull request by drixselecta**
Hello there,

This is a quick PR to update the PostGIS role for Debian Buster support.
Also, Wheezy support was dropped in order to simplify provisioning files.

Thank you for drifter,

Cédric

* This PR is an Improvement

- [/] Documentation is written
- [/] `parameters.yml.dist` is updated
- [/] `playbook.yml.dist` is updated
- [/] [Changelog](https://github.com/liip/drifter/blob/master/CHANGELOG.md) was updated

### CODE REVIEW

**Comment by drixselecta** [comment]
Happy new year! Is there a way to improve this PR to get it merged?

**Comment by LeBenLeBen** [comment]
@drixselecta Can you please rebase master?

**Comment by drixselecta** [comment]
Thanks for approving @LeBenLeBen! I just rebased on master.

**Comment by drixselecta** [comment]
Thank you @LeBenLeBen for merging 🎉!

**Pull request merged**
