### PR TITLE
Update ansible.cfg.dist to better handle unprivileged users

### PR DESCRIPTION
**Pull request by jeanmonod**
This is needed to install the `solr` role with the last ansible version I guess
* This PR is a : Bugfix

More info, see https://liip.slack.com/archives/C06E0G215/p1502869803000078

### CODE REVIEW

**Comment by kovacskri** [comment]
I had the same issue for a different project, and I had to delete become:solr on solr related tasks to fix this issue.

**Comment by sephii** [comment]
@jeanmonod for some reason the link you posted just opens the #drifter channel but doesn't point to any message so I can't check the details. Could you please explain why you need this, post an error trace and the playbook/parameters you used as well as the ansible + drifter versions?

I just tested the `solr` role with ansible 2.1.1.0 on a Debian jessie64 box, with Drifter master (e8e7d1003db57b99f097810b18bc0b3245fa7d44) and the `solr` role activated without any specific configuration, and it worked fine and I didn't get any error.

**Comment by jeanmonod** [comment]
This is the Slack extract:

---
I got an issue when provisioning the `solr` role on my new OSX laptop. The issue is 
    
    fatal: [default]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary
    files Ansible needs to create when becoming an unprivileged user. For information on working
    around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}`

When it request `become_user: solr` in https://github.com/liip/drifter/blob/master/provisioning/roles/solr/tasks/main.yml#L11 then ansible try to do a `EXEC /bin/sh -c 'chmod -R a+rX /tmp/ansible-tmp-1502869430.88-260350657822129/ && sleep 0'` and this is failing…

An easy work around is to add `allow_world_readable_tmpfiles = True` to the ansible.cfg. What about adding this into `ansible.cfg.dist`?

**Comment by sephii** [comment]
Thanks, I still couldn't reproduce the issue but I guess there's nothing to lose to merge this. :)

**Pull request merged**
