### PR TITLE
WIP: Examples multiple language versions

### PR DESCRIPTION
**Pull request by chregu**
Just provide some examples how to do "different language versions" or even "different boxes"

(the examples are for PHP 5.5/5.6/7.0, but are certainly useful for other languages as well)

### CODE REVIEW

**Comment by krtek4** [comment]
I am not sure about merging this one.

The idea of having examples is great, but I think we should wait to address the more general issues of documentation (see https://github.com/team-rawbot/rawbot-virtualization/issues/48) in order to determine where is the best place to put this.

If we decide to have some external documentation it would probably better to put it there.

(Also, I think the `ARGV[1]` thingy might not play really well with my code to detect the current provider, both seems kind of hacky, there's probably a better way to parse CLI arguments)

**Comment by chregu** [comment]
It's fine for me, when we don't include that for now. I agree it's hacky and I'm still searching for better solutions

**Comment by krtek4** [comment]
I just added a `docs` directory, I think this content could go in a new file `docs/tips/multiple-version.md` or something like that.

You also have to update the `mkdocs.yml` file to reference your file afterward.

**Comment by sephii** [comment]
@chregu I think it's great to have an `examples` directory for code examples. I would just move the README you put in the examples directory to a page in the `docs` directory which would explain the concept in detail, with references to the `examples` directory.

**Pull request closed without merging**
