### PR TITLE
Add Symfony1 Nginx site configuration

### PR DESCRIPTION
**Pull request by thePanz**
[Quick description of your PR and motivation.]

* This PR is a : New feature
* Link to the related issue if relevant

- [ ] Documentation is written
- [ ] `parameters.yml.dist` is updated
- [ ] `playbook.yml.dist` is updated
- [x] [Changelog](https://github.com/liip/drifter/blob/master/CHANGELOG.md) was updated

### CODE REVIEW

**Comment by sephii** [comment]
According to http://symfony.com/legacy Symfony 1 is not supported anymore since 2012, so I wouldn't merge this unless you have a very good reason for me to do it. If you need this for a particular project you can still put the config file in your project and set the `site_template` variable so that the nginx role uses it.

**Comment by thePanz** [comment]
Hi @sephii , I know it is not maintained anymore since 2012, but I was playing around with an old project written in SF1 and wanted to move it to SF2. I started by adding behat tests on the old one with the plan to re-run the same tests on the new SF2. With Drifter I was able to run the old SF1 project again (old version of PHP, mySQL and Solr) in few hours and without going crazy with my OS. I could even test if it is able to run correctly on newer versions of PHP without touching any line of code.

I understand your motivation against merging this PR,  but the aim of supporting SF1 is just to provide a working and testable environment, while build a migration to SF2 or other frameworks

**Comment by sephii** [comment]
I still think the usecase is too limited to be included in Drifter.

**Comment by sephii** [comment]
Closing this for now, sorry. I'm thinking (well, ok, credit for the idea goes to @krtek4) about creating a `drifter-extras` repository to include all kinds of roles with very limited scope, maybe this could be part of it.

**Pull request closed without merging**
